version: "3.12"

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db
    restart: always
    volumes:
      - ./backend:/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: frontend-serve
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    depends_on:
      - api
    restart: always

  db:
    image: postgres:16
    container_name: fastapi_auth_db
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
